version: "3.8"

services:
  minio:
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    command: minio server /data --console-address ':9001'
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
        reservations:
          cpus: '0.2'
          memory: 512M

  minio-init:
    image: minio/mc:latest
    depends_on:
      - minio
    entrypoint: >
      sh -c "
        mc alias set myminio http://minio:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD} && 
        mc mb myminio/mp4-to-gif &&
        mc anonymous set public myminio/mp4-to-gif
      "
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    deploy:
      replicas: 1
      restart_policy:
        condition: none
      resources:
        limits:
          cpus: '0.1'
          memory: 128M
        reservations:
          cpus: '0.1'
          memory: 64M


  redis:
    image: redis:7
    ports:
      - "6379:6379"
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.2'
          memory: 256M

  client:
    image: localhost:5000/image_client:latest
    environment:
      API_HOST: http://server:3000
    ports:
        - "4200:80"
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.2'
          memory: 128M

  server:
    image: localhost:5000/image_server:latest
    environment:
      SERVER_PORT: 3000
      REDIS_HOST: redis
      REDIS_PORT: 6379
      MINIO_ENDPOINT: http://minio:9000
      MINIO_PORT: 9000
      MINIO_ACCESS_KEY: admin
      MINIO_SECRET_KEY: admin123
      BUCKET_NAME: mp4-to-gif
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - minio
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.7'
          memory: 512M

  worker:
    image: localhost:5000/image_worker:latest
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      MINIO_ENDPOINT: http://minio:9000
      MINIO_PORT: 9000
      MINIO_ACCESS_KEY: admin
      MINIO_SECRET_KEY: admin123
      BUCKET_NAME: mp4-to-gif
    depends_on:
      - redis
      - minio
    deploy:
      replicas: 5
      restart_policy:
        condition: any
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M

volumes:
  minio_data:
